@startuml administrator
left to right direction
actor Administrator
rectangle "System" as system {
  (Access Admin Panel)
  (View User List)
  (Add New User)
  (Modify User Details)
  (Delete User)
  (End User Sessions)
  (Handle Transactions)
  (View Customer Cart)
  (Manage Inventory)
  (View Order History)
  (Cancel Order)
  (Customer Chat Support)
}
Administrator --> (Access Admin Panel)
Administrator --> (View User List)
Administrator --> (Add New User)
Administrator --> (Modify User Details)
Administrator --> (Delete User)
Administrator --> (End User Sessions)
Administrator --> (Handle Transactions)
Administrator --> (View Customer Cart)
Administrator --> (Manage Inventory)
Administrator --> (View Order History)
Administrator --> (Cancel Order)
Administrator --> (Customer Chat Support)
@enduml